/**
 * Registry of the real project media on disk under /public/images. Every
 * entry carries the intrinsic width/height (the source of truth for
 * aspect ratio, so next/image reserves space and never shifts layout) and
 * honest alt text describing what the file shows. `kind` distinguishes a
 * real construction photograph from a proposed design render / drawing —
 * renders must never be presented as as-built photographs.
 */

export type MediaKind = "photo" | "render" | "drawing" | "logo" | "map";

export interface RegisteredMediaAsset {
  readonly src: string;
  readonly alt: string;
  readonly width: number;
  readonly height: number;
  readonly kind: MediaKind;
  /** Whether the file exists under /public (always true here). */
  readonly onDisk: boolean;
  /** Confirmed as the correct, presentable asset. */
  readonly verified: boolean;
}

export const mediaRegistry = {
  // --- Hero slider ---------------------------------------------------------
  teshieLinkRemodel: {
    src: "/images/teshie-link-remodel.png",
    alt: "Aerial design visualisation of the Teshie Link Interchange, a landscaped cloverleaf junction linking the motorway with local roads",
    width: 3997,
    height: 2422,
    kind: "render",
    onDisk: true,
    verified: true,
  },
  flowerPotRemodel: {
    src: "/images/flower-pot-remodel.png",
    alt: "Design visualisation of a landscaped grade-separated flyover along the Accra–Tema corridor",
    width: 4184,
    height: 2383,
    kind: "render",
    onDisk: true,
    verified: true,
  },
  ogHeroBg: {
    src: "/images/og-hero-bg.jpg",
    alt: "Aerial view of the reconstructed Accra–Tema Motorway corridor with interchange and service roads",
    width: 1200,
    height: 630,
    kind: "render",
    onDisk: true,
    verified: true,
  },
  routeAlignmentMap: {
    src: "/images/route-alignment-map.png",
    alt: "Design visualisation of the Accra–Tema corridor showing carriageways and a toll plaza",
    width: 3840,
    height: 2160,
    kind: "render",
    onDisk: true,
    verified: true,
  },

  // --- Design page: proposed interchange renders ---------------------------
  heroCorridorAerial: {
    src: "/images/hero-corridor-aerial.jpg",
    alt: "Aerial design visualisation of the reconstructed Accra–Tema corridor: a multi-lane divided expressway with interchanges and service roads",
    width: 3840,
    height: 2160,
    kind: "render",
    onDisk: true,
    verified: true,
  },
  tettehQuarshieRender: {
    src: "/images/teshie-interchange-remodel.png",
    alt: "Design visualisation of the reconstructed Tetteh Quarshie Interchange with dual carriageways and roundabouts",
    width: 3558,
    height: 1938,
    kind: "render",
    onDisk: true,
    verified: true,
  },
  comm18Render: {
    src: "/images/comm-18-remodel.png",
    alt: "Design visualisation of the Community 18 Interchange showing the mainline flyover over a signalised cross road",
    width: 3299,
    height: 2474,
    kind: "render",
    onDisk: true,
    verified: true,
  },
  lashibiRender: {
    src: "/images/lashibi-remodel.png",
    alt: "Aerial design visualisation of the Lashibi Interchange corridor passing through a built-up area",
    width: 2599,
    height: 2380,
    kind: "render",
    onDisk: true,
    verified: true,
  },
  tettehQuarshieProposed: {
    src: "/images/tetteh-quarshie-proposed.png",
    alt: "Proposed design of the Tetteh Quarshie Interchange",
    width: 768,
    height: 488,
    kind: "render",
    onDisk: true,
    verified: true,
  },
  teshieLinkProposed: {
    src: "/images/teshie-link-proposed.png",
    alt: "Proposed design of the Teshie Link Interchange",
    width: 1871,
    height: 1045,
    kind: "render",
    onDisk: true,
    verified: true,
  },
  comm18Proposed: {
    src: "/images/comm-18-proposed.png",
    alt: "Proposed design of the Community 18 Interchange",
    width: 997,
    height: 625,
    kind: "render",
    onDisk: true,
    verified: true,
  },
  lashibiProposed: {
    src: "/images/lashibi-proposed.png",
    alt: "Proposed design of the Lashibi Interchange",
    width: 1201,
    height: 743,
    kind: "render",
    onDisk: true,
    verified: true,
  },
  tollPlazaRender: {
    src: "/images/toll-plaza1.png",
    alt: "Design visualisation of a corridor toll plaza with a canopy over the tolling lanes, showing the Accra and Tema directions",
    width: 3743,
    height: 2150,
    kind: "render",
    onDisk: true,
    verified: true,
  },
  tollPlazaRender2: {
    src: "/images/toll-plaza2.png",
    alt: "Design visualisation of a toll plaza and canopy along the reconstructed corridor",
    width: 3729,
    height: 2337,
    kind: "render",
    onDisk: true,
    verified: true,
  },
  designScheme: {
    src: "/images/design-scheme.png",
    alt: "Typical road cross-section drawing showing the divided carriageways, central reservation and pavement layers",
    width: 3962,
    height: 2075,
    kind: "drawing",
    onDisk: true,
    verified: true,
  },

  // --- Construction photographs (real) -------------------------------------
  bridgeTBeamLaunch: {
    src: "/images/progress-image1.png",
    alt: "A launching gantry positioning precast T-beams over a bridge span, with reinforcement projecting from the beams",
    width: 1213,
    height: 606,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  bridgeDeckPour: {
    src: "/images/progress-image2.png",
    alt: "Workers placing deck reinforcement on a bridge deck as a concrete pump delivers concrete",
    width: 1213,
    height: 606,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  bridgeDeckConcreting: {
    src: "/images/progress-image3.png",
    alt: "Bridge deck concreting beneath a red launching gantry, with a concrete pump and work crew on the deck",
    width: 2422,
    height: 2492,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  deckFinishing: {
    src: "/images/progress-image4.png",
    alt: "Work crew finishing a freshly poured concrete deck slab as a concrete pump boom reaches across it",
    width: 2362,
    height: 2513,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  underpassStructure: {
    src: "/images/progress-image5.png",
    alt: "Aerial view of a large reinforced-concrete underpass structure under construction beside a live road",
    width: 4400,
    height: 2475,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  rockFilling: {
    src: "/images/progress-image6.png",
    alt: "Aerial view of stockpiled rock fill and earthworks beside the corridor, with an underpass structure and traffic",
    width: 3886,
    height: 1853,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  corridorAerial: {
    src: "/images/progress-image7.png",
    alt: "Aerial view of the Section 1 corridor under construction, with traffic on partially completed carriageways",
    width: 3912,
    height: 1899,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  culvertEarthworks: {
    src: "/images/progress-image8.png",
    alt: "Aerial view of box-culvert construction and earth stockpiles alongside an existing road carrying traffic",
    width: 4362,
    height: 2054,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  streamCulvert: {
    src: "/images/progress-image9.png",
    alt: "Aerial view of culvert works beneath a road crossing a watercourse, with queuing traffic",
    width: 1213,
    height: 606,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  riverBridgeCulverts: {
    src: "/images/progress-image10.png",
    alt: "Aerial view of a river crossing with box and bridge culverts under construction on both sides of the road",
    width: 4400,
    height: 2475,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  retainingWall: {
    src: "/images/progress-image12.png",
    alt: "Night-time view of a long reinforcement cage for a retaining wall along an excavated section of the corridor",
    width: 4273,
    height: 2294,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  overpassPiers: {
    src: "/images/progress-image14.png",
    alt: "Aerial view of overpass pier and deck construction beside a live road, with a mobile crane and reinforcement cages",
    width: 4400,
    height: 2475,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  corridorPiers: {
    src: "/images/progress-image15.png",
    alt: "Aerial view of the corridor with new bridge piers and columns rising alongside traffic lanes",
    width: 4928,
    height: 2074,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  corridorGantries: {
    src: "/images/progress-image16.png",
    alt: "Aerial view of the corridor with two overpass deck structures under construction over the roadway",
    width: 4365,
    height: 2060,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  dustSpraying: {
    src: "/images/progress-image20.png",
    alt: "A water tanker spraying the road surface for dust suppression along the construction corridor",
    width: 960,
    height: 1280,
    kind: "photo",
    onDisk: true,
    verified: true,
  },

  // --- Aerial corridor construction photos (client-supplied) ---------------
  // Real drone photography of Section 1 works. Titles/alt describe only what
  // is verifiably visible; where a structure's exact function is unclear it
  // is described neutrally rather than named.
  atelJunctionUnderpass: {
    src: "/images/atel-images1.webp",
    alt: "Aerial view of a road underpass under construction at a junction, with a concrete base slab in the excavation and traffic diverted around it on temporary lanes",
    width: 2048,
    height: 1152,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  atelBridgeDeckRebar: {
    src: "/images/atel-images2.webp",
    alt: "Overhead aerial view of a bridge deck under construction, showing the deck reinforcement steel and workers in high-visibility gear on the span",
    width: 2048,
    height: 1152,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  atelPierConcreting: {
    src: "/images/atel-images3.webp",
    alt: "Aerial view of a bridge pier being concreted by a truck-mounted concrete pump beside the corridor, with traffic passing on the adjacent carriageway",
    width: 2048,
    height: 1152,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  atelOverpassDeck: {
    src: "/images/atel-images4.webp",
    alt: "Aerial view of an overpass deck under construction, wrapped in green safety netting, with a concrete pump delivering to workers on the deck",
    width: 2048,
    height: 1152,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  atelCorridorOverpass: {
    src: "/images/atel-images5.webp",
    alt: "Aerial view of the corridor with newly cast bridge piers rising beside a completed concrete carriageway carrying traffic",
    width: 2048,
    height: 1152,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  atelCorridorPiersWide: {
    src: "/images/atel-images6.webp",
    alt: "Wide aerial view along the corridor showing rows of new bridge piers and a partially completed concrete carriageway with traffic",
    width: 2048,
    height: 1152,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  atelOverpassCrossheads: {
    src: "/images/atel-images7.webp",
    alt: "Aerial view of completed overpass piers and crossheads straddling the corridor at dusk, with traffic on the road below",
    width: 2048,
    height: 1152,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  atelCarriagewaySection: {
    src: "/images/atel-images8.webp",
    alt: "Overhead aerial view of a completed concrete carriageway section with roadside ramp structures under construction on both sides",
    width: 2048,
    height: 1152,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  atelRoadsideRamps: {
    src: "/images/atel-images9.webp",
    alt: "Overhead aerial view of the corridor flanked by U-shaped reinforced-concrete ramp structures, with traffic on the central carriageway",
    width: 2048,
    height: 1152,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  atelJunctionRoundabout: {
    src: "/images/atel-images10.webp",
    alt: "Aerial view of a major junction on the corridor, with a completed underpass portal, a roundabout and diverted traffic through a built-up area",
    width: 2048,
    height: 1152,
    kind: "photo",
    onDisk: true,
    verified: true,
  },

  /**
   * ATEL logo mark used in the navigation rail and footer. Filename verified
   * on disk as lowercase `atel-logo.png` — Windows is case-insensitive but
   * Vercel's Linux build is not, so the casing here must match exactly.
   * NOTE: `logo-atel.png` also exists with identical dimensions and near
   * identical byte size — the two files appear to be duplicates. Worth
   * deleting one once the client confirms which is canonical.
   */
  atelLogoMark: {
    src: "/images/atel-logo.png",
    alt: "Accra–Tema Expressway Ltd. logo",
    width: 599,
    height: 496,
    kind: "logo",
    onDisk: true,
    verified: true,
  },

  // --- Stakeholder logos ---------------------------------------------------
  logoAtel: {
    src: "/images/logo-atel.png",
    alt: "Accra–Tema Expressway Limited logo",
    width: 599,
    height: 496,
    kind: "logo",
    onDisk: true,
    verified: true,
  },
  logoGha: {
    src: "/images/ghana-highway-authority.png",
    alt: "Ghana Highway Authority logo",
    width: 837,
    height: 250,
    kind: "logo",
    onDisk: true,
    verified: true,
  },
  logoGiif: {
    src: "/images/GIIF-logo_sm.png",
    alt: "Ghana Infrastructure Investment Fund logo",
    width: 274,
    height: 239,
    kind: "logo",
    onDisk: true,
    verified: true,
  },
  logoAssociatedConsultants: {
    src: "/images/associated-consultants.png",
    alt: "Associated Consultants Limited logo",
    width: 839,
    height: 288,
    kind: "logo",
    onDisk: true,
    verified: true,
  },
  logoMaripoma: {
    src: "/images/mariproma.png",
    alt: "Maripoma Enterprise Limited logo",
    width: 450,
    height: 103,
    kind: "logo",
    onDisk: true,
    verified: true,
  },

  // --- Progress photography, 28 August 2026 (client-supplied, captioned by chainage) ---
  progAshaiman: {
    src: "/images/progress-ashaiman.jpeg",
    alt: "Earthworks and construction activity at Ashaiman along the Section 1 corridor",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progBridgeKm10873A: {
    src: "/images/progress-bridge-km10-873-a.jpeg",
    alt: "Bridge construction at Km 10+873.6, left- and right-hand sides",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progBridgeKm10873B: {
    src: "/images/progress-bridge-km10-873-b.jpeg",
    alt: "Bridge construction at Km 10+873.6, second view of the left- and right-hand sides",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progBridgeKm13745A: {
    src: "/images/progress-bridge-km13-745-a.jpeg",
    alt: "Bridge construction at Km 13+745.1, left- and right-hand sides",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progBridgeKm13745B: {
    src: "/images/progress-bridge-km13-745-b.jpeg",
    alt: "Bridge construction at Km 13+745.1, second view of the left- and right-hand sides",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progBridgeKm16556A: {
    src: "/images/progress-bridge-km16-556-a.jpeg",
    alt: "Bridge construction at Km 16+556.2, left- and right-hand sides",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progBridgeKm16556B: {
    src: "/images/progress-bridge-km16-556-b.jpeg",
    alt: "Bridge construction at Km 16+556.2, second view of the left- and right-hand sides",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progCommunity18: {
    src: "/images/progress-community-18.jpeg",
    alt: "Construction works at the Community 18 interchange site",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progFootbridgeKm8050A: {
    src: "/images/progress-footbridge-km8-050-a.jpeg",
    alt: "Pedestrian footbridge No. 5 under construction at Km 8+050, left-hand side",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progFootbridgeKm8050B: {
    src: "/images/progress-footbridge-km8-050-b.jpeg",
    alt: "Pedestrian footbridge No. 5 at Km 8+050, second view of the left-hand side",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progFootbridgeKm8050C: {
    src: "/images/progress-footbridge-km8-050-c.jpeg",
    alt: "Pedestrian footbridge No. 5 at Km 8+050, third view of the left-hand side",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progFootbridgeKm9920: {
    src: "/images/progress-footbridge-km9-920.jpeg",
    alt: "Pedestrian footbridge at Km 9+920, left- and right-hand sides",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progRetainingKm12120A: {
    src: "/images/progress-retaining-km12-120-a.jpeg",
    alt: "Retaining wall construction at Km 12+120, left-hand side",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progRetainingKm12120B: {
    src: "/images/progress-retaining-km12-120-b.jpeg",
    alt: "Retaining wall construction at Km 12+120, second view of the left-hand side",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progRetainingKm12120C: {
    src: "/images/progress-retaining-km12-120-c.jpeg",
    alt: "Retaining wall construction at Km 12+120, third view of the left-hand side",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progRoadbedKm910: {
    src: "/images/progress-roadbed-km9-10.jpeg",
    alt: "Roadbed preparation between Km 9+000 and Km 10+000, left- and right-hand sides",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progSubbaseKm7600: {
    src: "/images/progress-subbase-km7-600.jpeg",
    alt: "Sub-base laying between Km 7+600 and Km 7+980, left-hand side",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progSubbaseKm8140: {
    src: "/images/progress-subbase-km8-140.jpeg",
    alt: "Sub-base laying between Km 8+140 and Km 8+340, left-hand side",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progSubgradeKm13300: {
    src: "/images/progress-subgrade-km13-300.jpeg",
    alt: "Subgrade preparation between Km 13+300 and Km 13+650, left- and right-hand sides",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progSubgradeKm17200: {
    src: "/images/progress-subgrade-km17-200.jpeg",
    alt: "Subgrade preparation between Km 17+200 and Km 17+500, left- and right-hand sides",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progSubgradeKm17500: {
    src: "/images/progress-subgrade-km17-500.jpeg",
    alt: "Subgrade preparation between Km 17+500 and Km 17+800, left- and right-hand sides",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progSubgradeKm17900: {
    src: "/images/progress-subgrade-km17-900.jpeg",
    alt: "Subgrade preparation between Km 17+500 and Km 17+900, left- and right-hand sides",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progSubgradeKm18000: {
    src: "/images/progress-subgrade-km18-000.jpeg",
    alt: "Subgrade preparation between Km 18+000 and Km 18+300, left- and right-hand sides",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progTBeam: {
    src: "/images/progress-t-beam.jpeg",
    alt: "Precast T-beams for bridge deck construction on the corridor",
    width: 1380,
    height: 1035,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progUnderpassKm2701: {
    src: "/images/progress-underpass-km2-701.jpeg",
    alt: "Underpass construction at Km 2+701",
    width: 1379,
    height: 1035,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progUnderpassKm16105A: {
    src: "/images/progress-underpass-km16-105-a.jpeg",
    alt: "Underpass construction at Km 16+105.039, left- and right-hand sides",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  progUnderpassKm16105B: {
    src: "/images/progress-underpass-km16-105-b.jpeg",
    alt: "Underpass construction at Km 16+105.039, second view of the left- and right-hand sides",
    width: 1380,
    height: 776,
    kind: "photo",
    onDisk: true,
    verified: true,
  },

  // --- Maripoma progress-of-works update, 28 August 2026 (client-supplied) ---
  // The four interchange photographs below are cropped from the supplied
  // presentation slides to the photograph itself (slide header, sidebar and
  // label banners removed). Originals kept as progress-update-2..5.jpeg.
  progressChartAug2026: {
    src: "/images/progress-update-1.jpeg",
    alt: "Maripoma chart of physical progress for the 19.5 km Section 1 works, rising month by month from 38% in January 2026 to 52% in August 2026",
    width: 800,
    height: 450,
    kind: "drawing",
    onDisk: true,
    verified: true,
  },
  teshieLinkDiversionWalls: {
    src: "/images/teshie-link-diversion-walls.jpeg",
    alt: "Construction of traffic-diversion walls on the left-hand side at Teshie Link Interchange, Km 6+363, with traffic passing between Accra and Tema",
    width: 703,
    height: 355,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  teshieLinkFootingWall: {
    src: "/images/teshie-link-footing-wall.jpeg",
    alt: "Footing wall construction on the right-hand side at Teshie Link Interchange, Km 6+380, with an excavator working alongside the corridor",
    width: 698,
    height: 347,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  comm18FootingWall: {
    src: "/images/comm18-footing-wall.jpeg",
    alt: "Footing wall construction on the right-hand side at Community 18 Interchange between Km 12+010 and Km 12+910, with live traffic in both directions",
    width: 704,
    height: 337,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  comm18Underpass: {
    src: "/images/comm18-underpass.jpeg",
    alt: "Underpass construction at Community 18 Interchange, Km 12+350, showing the completed reinforced-concrete box on both sides of the corridor",
    width: 712,
    height: 348,
    kind: "photo",
    onDisk: true,
    verified: true,
  },
  workPlanSep2026PageOne: {
    src: "/images/progress-update-6.jpeg",
    alt: "Maripoma work plan for September 2026, page one: planned quantities for preliminary studies, earthworks, concrete works and road paving",
    width: 800,
    height: 450,
    kind: "drawing",
    onDisk: true,
    verified: true,
  },
  workPlanSep2026PageTwo: {
    src: "/images/progress-update-7.jpeg",
    alt: "Maripoma work plan for September 2026, page two: planned quantities for pavement, interchange structures, footbridges and drainage",
    width: 800,
    height: 450,
    kind: "drawing",
    onDisk: true,
    verified: true,
  },

} as const satisfies Record<string, RegisteredMediaAsset>;

export type MediaKey = keyof typeof mediaRegistry;

/** Whether a registry asset is safe to render as a real, confirmed image. */
export function isRenderable(asset: RegisteredMediaAsset): boolean {
  return asset.onDisk && asset.verified;
}
